// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/Aurora.tsx": () => import("../components/mockups/hero-variants/Aurora.tsx"),
  "./components/mockups/hero-variants/Crystalline.tsx": () => import("../components/mockups/hero-variants/Crystalline.tsx"),
  "./components/mockups/hero-variants/DeepSpace.tsx": () => import("../components/mockups/hero-variants/DeepSpace.tsx")
};
