/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as SterovaAdminRouteImport } from './routes/sterova-admin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as SterovaAdminIndexRouteImport } from './routes/sterova-admin.index'
import { Route as SterovaAdminCmsRouteImport } from './routes/sterova-admin._cms'
import { Route as SterovaAdminCmsCategoriesRouteImport } from './routes/sterova-admin._cms.categories'
import { Route as SterovaAdminCmsDashboardRouteImport } from './routes/sterova-admin._cms.dashboard'
import { Route as SterovaAdminCmsMessagesRouteImport } from './routes/sterova-admin._cms.messages'
import { Route as SterovaAdminCmsProjectsRouteImport } from './routes/sterova-admin._cms.projects'
import { Route as SterovaAdminCmsResultsRouteImport } from './routes/sterova-admin._cms.results'
import { Route as SterovaAdminCmsReviewsRouteImport } from './routes/sterova-admin._cms.reviews'
import { Route as SterovaAdminCmsSessionsRouteImport } from './routes/sterova-admin._cms.sessions'
import { Route as SterovaAdminCmsTeamRouteImport } from './routes/sterova-admin._cms.team'
import { Route as SterovaAdminCmsPostsIndexRouteImport } from './routes/sterova-admin._cms.posts.index'
import { Route as SterovaAdminCmsPostsIdRouteImport } from './routes/sterova-admin._cms.posts.$id'
import { Route as SterovaAdminCmsPostsNewRouteImport } from './routes/sterova-admin._cms.posts.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const SterovaAdminRoute = SterovaAdminRouteImport.update({
  id: '/sterova-admin',
  path: '/sterova-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SterovaAdminIndexRoute = SterovaAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SterovaAdminRoute,
} as any)
const SterovaAdminCmsRoute = SterovaAdminCmsRouteImport.update({
  id: '/_cms',
  getParentRoute: () => SterovaAdminRoute,
} as any)
const SterovaAdminCmsCategoriesRoute =
  SterovaAdminCmsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsDashboardRoute =
  SterovaAdminCmsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsMessagesRoute = SterovaAdminCmsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsProjectsRoute = SterovaAdminCmsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsResultsRoute = SterovaAdminCmsResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsReviewsRoute = SterovaAdminCmsReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsSessionsRoute = SterovaAdminCmsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsTeamRoute = SterovaAdminCmsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsPostsIndexRoute =
  SterovaAdminCmsPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsPostsIdRoute = SterovaAdminCmsPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsPostsNewRoute = SterovaAdminCmsPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/sterova-admin': typeof SterovaAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/sterova-admin/': typeof SterovaAdminIndexRoute
  '/sterova-admin/categories': typeof SterovaAdminCmsCategoriesRoute
  '/sterova-admin/dashboard': typeof SterovaAdminCmsDashboardRoute
  '/sterova-admin/messages': typeof SterovaAdminCmsMessagesRoute
  '/sterova-admin/projects': typeof SterovaAdminCmsProjectsRoute
  '/sterova-admin/results': typeof SterovaAdminCmsResultsRoute
  '/sterova-admin/reviews': typeof SterovaAdminCmsReviewsRoute
  '/sterova-admin/sessions': typeof SterovaAdminCmsSessionsRoute
  '/sterova-admin/team': typeof SterovaAdminCmsTeamRoute
  '/sterova-admin/posts/$id': typeof SterovaAdminCmsPostsIdRoute
  '/sterova-admin/posts/new': typeof SterovaAdminCmsPostsNewRoute
  '/sterova-admin/posts/': typeof SterovaAdminCmsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sterova-admin': typeof SterovaAdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/sterova-admin/categories': typeof SterovaAdminCmsCategoriesRoute
  '/sterova-admin/dashboard': typeof SterovaAdminCmsDashboardRoute
  '/sterova-admin/messages': typeof SterovaAdminCmsMessagesRoute
  '/sterova-admin/projects': typeof SterovaAdminCmsProjectsRoute
  '/sterova-admin/results': typeof SterovaAdminCmsResultsRoute
  '/sterova-admin/reviews': typeof SterovaAdminCmsReviewsRoute
  '/sterova-admin/sessions': typeof SterovaAdminCmsSessionsRoute
  '/sterova-admin/team': typeof SterovaAdminCmsTeamRoute
  '/sterova-admin/posts/$id': typeof SterovaAdminCmsPostsIdRoute
  '/sterova-admin/posts/new': typeof SterovaAdminCmsPostsNewRoute
  '/sterova-admin/posts': typeof SterovaAdminCmsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/sterova-admin': typeof SterovaAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sterova-admin/_cms': typeof SterovaAdminCmsRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/sterova-admin/': typeof SterovaAdminIndexRoute
  '/sterova-admin/_cms/categories': typeof SterovaAdminCmsCategoriesRoute
  '/sterova-admin/_cms/dashboard': typeof SterovaAdminCmsDashboardRoute
  '/sterova-admin/_cms/messages': typeof SterovaAdminCmsMessagesRoute
  '/sterova-admin/_cms/projects': typeof SterovaAdminCmsProjectsRoute
  '/sterova-admin/_cms/results': typeof SterovaAdminCmsResultsRoute
  '/sterova-admin/_cms/reviews': typeof SterovaAdminCmsReviewsRoute
  '/sterova-admin/_cms/sessions': typeof SterovaAdminCmsSessionsRoute
  '/sterova-admin/_cms/team': typeof SterovaAdminCmsTeamRoute
  '/sterova-admin/_cms/posts/$id': typeof SterovaAdminCmsPostsIdRoute
  '/sterova-admin/_cms/posts/new': typeof SterovaAdminCmsPostsNewRoute
  '/sterova-admin/_cms/posts/': typeof SterovaAdminCmsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/sterova-admin'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
    | '/sterova-admin/'
    | '/sterova-admin/categories'
    | '/sterova-admin/dashboard'
    | '/sterova-admin/messages'
    | '/sterova-admin/projects'
    | '/sterova-admin/results'
    | '/sterova-admin/reviews'
    | '/sterova-admin/sessions'
    | '/sterova-admin/team'
    | '/sterova-admin/posts/$id'
    | '/sterova-admin/posts/new'
    | '/sterova-admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/terms'
    | '/blog/$slug'
    | '/sterova-admin'
    | '/blog'
    | '/sterova-admin/categories'
    | '/sterova-admin/dashboard'
    | '/sterova-admin/messages'
    | '/sterova-admin/projects'
    | '/sterova-admin/results'
    | '/sterova-admin/reviews'
    | '/sterova-admin/sessions'
    | '/sterova-admin/team'
    | '/sterova-admin/posts/$id'
    | '/sterova-admin/posts/new'
    | '/sterova-admin/posts'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/sterova-admin'
    | '/terms'
    | '/blog/$slug'
    | '/sterova-admin/_cms'
    | '/blog/'
    | '/sterova-admin/'
    | '/sterova-admin/_cms/categories'
    | '/sterova-admin/_cms/dashboard'
    | '/sterova-admin/_cms/messages'
    | '/sterova-admin/_cms/projects'
    | '/sterova-admin/_cms/results'
    | '/sterova-admin/_cms/reviews'
    | '/sterova-admin/_cms/sessions'
    | '/sterova-admin/_cms/team'
    | '/sterova-admin/_cms/posts/$id'
    | '/sterova-admin/_cms/posts/new'
    | '/sterova-admin/_cms/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartProjectRoute: typeof StartProjectRoute
  SterovaAdminRoute: typeof SterovaAdminRouteWithChildren
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sterova-admin': {
      id: '/sterova-admin'
      path: '/sterova-admin'
      fullPath: '/sterova-admin'
      preLoaderRoute: typeof SterovaAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sterova-admin/': {
      id: '/sterova-admin/'
      path: '/'
      fullPath: '/sterova-admin/'
      preLoaderRoute: typeof SterovaAdminIndexRouteImport
      parentRoute: typeof SterovaAdminRoute
    }
    '/sterova-admin/_cms': {
      id: '/sterova-admin/_cms'
      path: ''
      fullPath: '/sterova-admin'
      preLoaderRoute: typeof SterovaAdminCmsRouteImport
      parentRoute: typeof SterovaAdminRoute
    }
    '/sterova-admin/_cms/categories': {
      id: '/sterova-admin/_cms/categories'
      path: '/categories'
      fullPath: '/sterova-admin/categories'
      preLoaderRoute: typeof SterovaAdminCmsCategoriesRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/dashboard': {
      id: '/sterova-admin/_cms/dashboard'
      path: '/dashboard'
      fullPath: '/sterova-admin/dashboard'
      preLoaderRoute: typeof SterovaAdminCmsDashboardRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/messages': {
      id: '/sterova-admin/_cms/messages'
      path: '/messages'
      fullPath: '/sterova-admin/messages'
      preLoaderRoute: typeof SterovaAdminCmsMessagesRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/projects': {
      id: '/sterova-admin/_cms/projects'
      path: '/projects'
      fullPath: '/sterova-admin/projects'
      preLoaderRoute: typeof SterovaAdminCmsProjectsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/results': {
      id: '/sterova-admin/_cms/results'
      path: '/results'
      fullPath: '/sterova-admin/results'
      preLoaderRoute: typeof SterovaAdminCmsResultsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/reviews': {
      id: '/sterova-admin/_cms/reviews'
      path: '/reviews'
      fullPath: '/sterova-admin/reviews'
      preLoaderRoute: typeof SterovaAdminCmsReviewsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/sessions': {
      id: '/sterova-admin/_cms/sessions'
      path: '/sessions'
      fullPath: '/sterova-admin/sessions'
      preLoaderRoute: typeof SterovaAdminCmsSessionsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/team': {
      id: '/sterova-admin/_cms/team'
      path: '/team'
      fullPath: '/sterova-admin/team'
      preLoaderRoute: typeof SterovaAdminCmsTeamRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/posts/': {
      id: '/sterova-admin/_cms/posts/'
      path: '/posts'
      fullPath: '/sterova-admin/posts/'
      preLoaderRoute: typeof SterovaAdminCmsPostsIndexRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/posts/$id': {
      id: '/sterova-admin/_cms/posts/$id'
      path: '/posts/$id'
      fullPath: '/sterova-admin/posts/$id'
      preLoaderRoute: typeof SterovaAdminCmsPostsIdRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/posts/new': {
      id: '/sterova-admin/_cms/posts/new'
      path: '/posts/new'
      fullPath: '/sterova-admin/posts/new'
      preLoaderRoute: typeof SterovaAdminCmsPostsNewRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
  }
}

interface SterovaAdminCmsRouteChildren {
  SterovaAdminCmsCategoriesRoute: typeof SterovaAdminCmsCategoriesRoute
  SterovaAdminCmsDashboardRoute: typeof SterovaAdminCmsDashboardRoute
  SterovaAdminCmsMessagesRoute: typeof SterovaAdminCmsMessagesRoute
  SterovaAdminCmsProjectsRoute: typeof SterovaAdminCmsProjectsRoute
  SterovaAdminCmsResultsRoute: typeof SterovaAdminCmsResultsRoute
  SterovaAdminCmsReviewsRoute: typeof SterovaAdminCmsReviewsRoute
  SterovaAdminCmsSessionsRoute: typeof SterovaAdminCmsSessionsRoute
  SterovaAdminCmsTeamRoute: typeof SterovaAdminCmsTeamRoute
  SterovaAdminCmsPostsIdRoute: typeof SterovaAdminCmsPostsIdRoute
  SterovaAdminCmsPostsNewRoute: typeof SterovaAdminCmsPostsNewRoute
  SterovaAdminCmsPostsIndexRoute: typeof SterovaAdminCmsPostsIndexRoute
}

const SterovaAdminCmsRouteChildren: SterovaAdminCmsRouteChildren = {
  SterovaAdminCmsCategoriesRoute: SterovaAdminCmsCategoriesRoute,
  SterovaAdminCmsDashboardRoute: SterovaAdminCmsDashboardRoute,
  SterovaAdminCmsMessagesRoute: SterovaAdminCmsMessagesRoute,
  SterovaAdminCmsProjectsRoute: SterovaAdminCmsProjectsRoute,
  SterovaAdminCmsResultsRoute: SterovaAdminCmsResultsRoute,
  SterovaAdminCmsReviewsRoute: SterovaAdminCmsReviewsRoute,
  SterovaAdminCmsSessionsRoute: SterovaAdminCmsSessionsRoute,
  SterovaAdminCmsTeamRoute: SterovaAdminCmsTeamRoute,
  SterovaAdminCmsPostsIdRoute: SterovaAdminCmsPostsIdRoute,
  SterovaAdminCmsPostsNewRoute: SterovaAdminCmsPostsNewRoute,
  SterovaAdminCmsPostsIndexRoute: SterovaAdminCmsPostsIndexRoute,
}

const SterovaAdminCmsRouteWithChildren = SterovaAdminCmsRoute._addFileChildren(
  SterovaAdminCmsRouteChildren,
)

interface SterovaAdminRouteChildren {
  SterovaAdminCmsRoute: typeof SterovaAdminCmsRouteWithChildren
  SterovaAdminIndexRoute: typeof SterovaAdminIndexRoute
}

const SterovaAdminRouteChildren: SterovaAdminRouteChildren = {
  SterovaAdminCmsRoute: SterovaAdminCmsRouteWithChildren,
  SterovaAdminIndexRoute: SterovaAdminIndexRoute,
}

const SterovaAdminRouteWithChildren = SterovaAdminRoute._addFileChildren(
  SterovaAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartProjectRoute: StartProjectRoute,
  SterovaAdminRoute: SterovaAdminRouteWithChildren,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
