/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as SterovaAdminRouteImport } from './routes/sterova-admin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as SterovaAdminIndexRouteImport } from './routes/sterova-admin.index'
import { Route as SterovaAdminCmsRouteImport } from './routes/sterova-admin._cms'
import { Route as SterovaAdminCmsAccessRouteImport } from './routes/sterova-admin._cms.access'
import { Route as SterovaAdminCmsBrandLinksRouteImport } from './routes/sterova-admin._cms.brand-links'
import { Route as SterovaAdminCmsCareersRouteImport } from './routes/sterova-admin._cms.careers'
import { Route as SterovaAdminCmsCategoriesRouteImport } from './routes/sterova-admin._cms.categories'
import { Route as SterovaAdminCmsChatAnalyticsRouteImport } from './routes/sterova-admin._cms.chat-analytics'
import { Route as SterovaAdminCmsChatLeadsRouteImport } from './routes/sterova-admin._cms.chat-leads'
import { Route as SterovaAdminCmsConsultationsRouteImport } from './routes/sterova-admin._cms.consultations'
import { Route as SterovaAdminCmsDashboardRouteImport } from './routes/sterova-admin._cms.dashboard'
import { Route as SterovaAdminCmsEstimatesRouteImport } from './routes/sterova-admin._cms.estimates'
import { Route as SterovaAdminCmsMessagesRouteImport } from './routes/sterova-admin._cms.messages'
import { Route as SterovaAdminCmsNotificationsRouteImport } from './routes/sterova-admin._cms.notifications'
import { Route as SterovaAdminCmsProjectsRouteImport } from './routes/sterova-admin._cms.projects'
import { Route as SterovaAdminCmsResultsRouteImport } from './routes/sterova-admin._cms.results'
import { Route as SterovaAdminCmsReviewsRouteImport } from './routes/sterova-admin._cms.reviews'
import { Route as SterovaAdminCmsSessionsRouteImport } from './routes/sterova-admin._cms.sessions'
import { Route as SterovaAdminCmsSettingsRouteImport } from './routes/sterova-admin._cms.settings'
import { Route as SterovaAdminCmsTeamRouteImport } from './routes/sterova-admin._cms.team'
import { Route as SterovaAdminCmsTestimonialsRouteImport } from './routes/sterova-admin._cms.testimonials'
import { Route as SterovaAdminCmsPostsIndexRouteImport } from './routes/sterova-admin._cms.posts.index'
import { Route as SterovaAdminCmsPostsIdRouteImport } from './routes/sterova-admin._cms.posts.$id'
import { Route as SterovaAdminCmsPostsNewRouteImport } from './routes/sterova-admin._cms.posts.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const SterovaAdminRoute = SterovaAdminRouteImport.update({
  id: '/sterova-admin',
  path: '/sterova-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SterovaAdminIndexRoute = SterovaAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SterovaAdminRoute,
} as any)
const SterovaAdminCmsRoute = SterovaAdminCmsRouteImport.update({
  id: '/_cms',
  getParentRoute: () => SterovaAdminRoute,
} as any)
const SterovaAdminCmsAccessRoute = SterovaAdminCmsAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsBrandLinksRoute =
  SterovaAdminCmsBrandLinksRouteImport.update({
    id: '/brand-links',
    path: '/brand-links',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsCareersRoute = SterovaAdminCmsCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsCategoriesRoute =
  SterovaAdminCmsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsChatAnalyticsRoute =
  SterovaAdminCmsChatAnalyticsRouteImport.update({
    id: '/chat-analytics',
    path: '/chat-analytics',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsChatLeadsRoute =
  SterovaAdminCmsChatLeadsRouteImport.update({
    id: '/chat-leads',
    path: '/chat-leads',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsConsultationsRoute =
  SterovaAdminCmsConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsDashboardRoute =
  SterovaAdminCmsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsEstimatesRoute =
  SterovaAdminCmsEstimatesRouteImport.update({
    id: '/estimates',
    path: '/estimates',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsMessagesRoute = SterovaAdminCmsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsNotificationsRoute =
  SterovaAdminCmsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsProjectsRoute = SterovaAdminCmsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsResultsRoute = SterovaAdminCmsResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsReviewsRoute = SterovaAdminCmsReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsSessionsRoute = SterovaAdminCmsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsSettingsRoute = SterovaAdminCmsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsTeamRoute = SterovaAdminCmsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsTestimonialsRoute =
  SterovaAdminCmsTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsPostsIndexRoute =
  SterovaAdminCmsPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => SterovaAdminCmsRoute,
  } as any)
const SterovaAdminCmsPostsIdRoute = SterovaAdminCmsPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)
const SterovaAdminCmsPostsNewRoute = SterovaAdminCmsPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => SterovaAdminCmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/sterova-admin': typeof SterovaAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/sterova-admin/': typeof SterovaAdminIndexRoute
  '/sterova-admin/access': typeof SterovaAdminCmsAccessRoute
  '/sterova-admin/brand-links': typeof SterovaAdminCmsBrandLinksRoute
  '/sterova-admin/careers': typeof SterovaAdminCmsCareersRoute
  '/sterova-admin/categories': typeof SterovaAdminCmsCategoriesRoute
  '/sterova-admin/chat-analytics': typeof SterovaAdminCmsChatAnalyticsRoute
  '/sterova-admin/chat-leads': typeof SterovaAdminCmsChatLeadsRoute
  '/sterova-admin/consultations': typeof SterovaAdminCmsConsultationsRoute
  '/sterova-admin/dashboard': typeof SterovaAdminCmsDashboardRoute
  '/sterova-admin/estimates': typeof SterovaAdminCmsEstimatesRoute
  '/sterova-admin/messages': typeof SterovaAdminCmsMessagesRoute
  '/sterova-admin/notifications': typeof SterovaAdminCmsNotificationsRoute
  '/sterova-admin/projects': typeof SterovaAdminCmsProjectsRoute
  '/sterova-admin/results': typeof SterovaAdminCmsResultsRoute
  '/sterova-admin/reviews': typeof SterovaAdminCmsReviewsRoute
  '/sterova-admin/sessions': typeof SterovaAdminCmsSessionsRoute
  '/sterova-admin/settings': typeof SterovaAdminCmsSettingsRoute
  '/sterova-admin/team': typeof SterovaAdminCmsTeamRoute
  '/sterova-admin/testimonials': typeof SterovaAdminCmsTestimonialsRoute
  '/sterova-admin/posts/$id': typeof SterovaAdminCmsPostsIdRoute
  '/sterova-admin/posts/new': typeof SterovaAdminCmsPostsNewRoute
  '/sterova-admin/posts/': typeof SterovaAdminCmsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sterova-admin': typeof SterovaAdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/sterova-admin/access': typeof SterovaAdminCmsAccessRoute
  '/sterova-admin/brand-links': typeof SterovaAdminCmsBrandLinksRoute
  '/sterova-admin/careers': typeof SterovaAdminCmsCareersRoute
  '/sterova-admin/categories': typeof SterovaAdminCmsCategoriesRoute
  '/sterova-admin/chat-analytics': typeof SterovaAdminCmsChatAnalyticsRoute
  '/sterova-admin/chat-leads': typeof SterovaAdminCmsChatLeadsRoute
  '/sterova-admin/consultations': typeof SterovaAdminCmsConsultationsRoute
  '/sterova-admin/dashboard': typeof SterovaAdminCmsDashboardRoute
  '/sterova-admin/estimates': typeof SterovaAdminCmsEstimatesRoute
  '/sterova-admin/messages': typeof SterovaAdminCmsMessagesRoute
  '/sterova-admin/notifications': typeof SterovaAdminCmsNotificationsRoute
  '/sterova-admin/projects': typeof SterovaAdminCmsProjectsRoute
  '/sterova-admin/results': typeof SterovaAdminCmsResultsRoute
  '/sterova-admin/reviews': typeof SterovaAdminCmsReviewsRoute
  '/sterova-admin/sessions': typeof SterovaAdminCmsSessionsRoute
  '/sterova-admin/settings': typeof SterovaAdminCmsSettingsRoute
  '/sterova-admin/team': typeof SterovaAdminCmsTeamRoute
  '/sterova-admin/testimonials': typeof SterovaAdminCmsTestimonialsRoute
  '/sterova-admin/posts/$id': typeof SterovaAdminCmsPostsIdRoute
  '/sterova-admin/posts/new': typeof SterovaAdminCmsPostsNewRoute
  '/sterova-admin/posts': typeof SterovaAdminCmsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/estimate': typeof EstimateRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-project': typeof StartProjectRoute
  '/sterova-admin': typeof SterovaAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sterova-admin/_cms': typeof SterovaAdminCmsRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/sterova-admin/': typeof SterovaAdminIndexRoute
  '/sterova-admin/_cms/access': typeof SterovaAdminCmsAccessRoute
  '/sterova-admin/_cms/brand-links': typeof SterovaAdminCmsBrandLinksRoute
  '/sterova-admin/_cms/careers': typeof SterovaAdminCmsCareersRoute
  '/sterova-admin/_cms/categories': typeof SterovaAdminCmsCategoriesRoute
  '/sterova-admin/_cms/chat-analytics': typeof SterovaAdminCmsChatAnalyticsRoute
  '/sterova-admin/_cms/chat-leads': typeof SterovaAdminCmsChatLeadsRoute
  '/sterova-admin/_cms/consultations': typeof SterovaAdminCmsConsultationsRoute
  '/sterova-admin/_cms/dashboard': typeof SterovaAdminCmsDashboardRoute
  '/sterova-admin/_cms/estimates': typeof SterovaAdminCmsEstimatesRoute
  '/sterova-admin/_cms/messages': typeof SterovaAdminCmsMessagesRoute
  '/sterova-admin/_cms/notifications': typeof SterovaAdminCmsNotificationsRoute
  '/sterova-admin/_cms/projects': typeof SterovaAdminCmsProjectsRoute
  '/sterova-admin/_cms/results': typeof SterovaAdminCmsResultsRoute
  '/sterova-admin/_cms/reviews': typeof SterovaAdminCmsReviewsRoute
  '/sterova-admin/_cms/sessions': typeof SterovaAdminCmsSessionsRoute
  '/sterova-admin/_cms/settings': typeof SterovaAdminCmsSettingsRoute
  '/sterova-admin/_cms/team': typeof SterovaAdminCmsTeamRoute
  '/sterova-admin/_cms/testimonials': typeof SterovaAdminCmsTestimonialsRoute
  '/sterova-admin/_cms/posts/$id': typeof SterovaAdminCmsPostsIdRoute
  '/sterova-admin/_cms/posts/new': typeof SterovaAdminCmsPostsNewRoute
  '/sterova-admin/_cms/posts/': typeof SterovaAdminCmsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/estimate'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/sterova-admin'
    | '/terms'
    | '/blog/$slug'
    | '/blog/'
    | '/sterova-admin/'
    | '/sterova-admin/access'
    | '/sterova-admin/brand-links'
    | '/sterova-admin/careers'
    | '/sterova-admin/categories'
    | '/sterova-admin/chat-analytics'
    | '/sterova-admin/chat-leads'
    | '/sterova-admin/consultations'
    | '/sterova-admin/dashboard'
    | '/sterova-admin/estimates'
    | '/sterova-admin/messages'
    | '/sterova-admin/notifications'
    | '/sterova-admin/projects'
    | '/sterova-admin/results'
    | '/sterova-admin/reviews'
    | '/sterova-admin/sessions'
    | '/sterova-admin/settings'
    | '/sterova-admin/team'
    | '/sterova-admin/testimonials'
    | '/sterova-admin/posts/$id'
    | '/sterova-admin/posts/new'
    | '/sterova-admin/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/estimate'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/terms'
    | '/blog/$slug'
    | '/sterova-admin'
    | '/blog'
    | '/sterova-admin/access'
    | '/sterova-admin/brand-links'
    | '/sterova-admin/careers'
    | '/sterova-admin/categories'
    | '/sterova-admin/chat-analytics'
    | '/sterova-admin/chat-leads'
    | '/sterova-admin/consultations'
    | '/sterova-admin/dashboard'
    | '/sterova-admin/estimates'
    | '/sterova-admin/messages'
    | '/sterova-admin/notifications'
    | '/sterova-admin/projects'
    | '/sterova-admin/results'
    | '/sterova-admin/reviews'
    | '/sterova-admin/sessions'
    | '/sterova-admin/settings'
    | '/sterova-admin/team'
    | '/sterova-admin/testimonials'
    | '/sterova-admin/posts/$id'
    | '/sterova-admin/posts/new'
    | '/sterova-admin/posts'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/estimate'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/start-project'
    | '/sterova-admin'
    | '/terms'
    | '/blog/$slug'
    | '/sterova-admin/_cms'
    | '/blog/'
    | '/sterova-admin/'
    | '/sterova-admin/_cms/access'
    | '/sterova-admin/_cms/brand-links'
    | '/sterova-admin/_cms/careers'
    | '/sterova-admin/_cms/categories'
    | '/sterova-admin/_cms/chat-analytics'
    | '/sterova-admin/_cms/chat-leads'
    | '/sterova-admin/_cms/consultations'
    | '/sterova-admin/_cms/dashboard'
    | '/sterova-admin/_cms/estimates'
    | '/sterova-admin/_cms/messages'
    | '/sterova-admin/_cms/notifications'
    | '/sterova-admin/_cms/projects'
    | '/sterova-admin/_cms/results'
    | '/sterova-admin/_cms/reviews'
    | '/sterova-admin/_cms/sessions'
    | '/sterova-admin/_cms/settings'
    | '/sterova-admin/_cms/team'
    | '/sterova-admin/_cms/testimonials'
    | '/sterova-admin/_cms/posts/$id'
    | '/sterova-admin/_cms/posts/new'
    | '/sterova-admin/_cms/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EstimateRoute: typeof EstimateRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartProjectRoute: typeof StartProjectRoute
  SterovaAdminRoute: typeof SterovaAdminRouteWithChildren
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sterova-admin': {
      id: '/sterova-admin'
      path: '/sterova-admin'
      fullPath: '/sterova-admin'
      preLoaderRoute: typeof SterovaAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sterova-admin/': {
      id: '/sterova-admin/'
      path: '/'
      fullPath: '/sterova-admin/'
      preLoaderRoute: typeof SterovaAdminIndexRouteImport
      parentRoute: typeof SterovaAdminRoute
    }
    '/sterova-admin/_cms': {
      id: '/sterova-admin/_cms'
      path: ''
      fullPath: '/sterova-admin'
      preLoaderRoute: typeof SterovaAdminCmsRouteImport
      parentRoute: typeof SterovaAdminRoute
    }
    '/sterova-admin/_cms/access': {
      id: '/sterova-admin/_cms/access'
      path: '/access'
      fullPath: '/sterova-admin/access'
      preLoaderRoute: typeof SterovaAdminCmsAccessRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/brand-links': {
      id: '/sterova-admin/_cms/brand-links'
      path: '/brand-links'
      fullPath: '/sterova-admin/brand-links'
      preLoaderRoute: typeof SterovaAdminCmsBrandLinksRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/careers': {
      id: '/sterova-admin/_cms/careers'
      path: '/careers'
      fullPath: '/sterova-admin/careers'
      preLoaderRoute: typeof SterovaAdminCmsCareersRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/categories': {
      id: '/sterova-admin/_cms/categories'
      path: '/categories'
      fullPath: '/sterova-admin/categories'
      preLoaderRoute: typeof SterovaAdminCmsCategoriesRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/chat-analytics': {
      id: '/sterova-admin/_cms/chat-analytics'
      path: '/chat-analytics'
      fullPath: '/sterova-admin/chat-analytics'
      preLoaderRoute: typeof SterovaAdminCmsChatAnalyticsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/chat-leads': {
      id: '/sterova-admin/_cms/chat-leads'
      path: '/chat-leads'
      fullPath: '/sterova-admin/chat-leads'
      preLoaderRoute: typeof SterovaAdminCmsChatLeadsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/consultations': {
      id: '/sterova-admin/_cms/consultations'
      path: '/consultations'
      fullPath: '/sterova-admin/consultations'
      preLoaderRoute: typeof SterovaAdminCmsConsultationsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/dashboard': {
      id: '/sterova-admin/_cms/dashboard'
      path: '/dashboard'
      fullPath: '/sterova-admin/dashboard'
      preLoaderRoute: typeof SterovaAdminCmsDashboardRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/estimates': {
      id: '/sterova-admin/_cms/estimates'
      path: '/estimates'
      fullPath: '/sterova-admin/estimates'
      preLoaderRoute: typeof SterovaAdminCmsEstimatesRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/messages': {
      id: '/sterova-admin/_cms/messages'
      path: '/messages'
      fullPath: '/sterova-admin/messages'
      preLoaderRoute: typeof SterovaAdminCmsMessagesRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/notifications': {
      id: '/sterova-admin/_cms/notifications'
      path: '/notifications'
      fullPath: '/sterova-admin/notifications'
      preLoaderRoute: typeof SterovaAdminCmsNotificationsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/projects': {
      id: '/sterova-admin/_cms/projects'
      path: '/projects'
      fullPath: '/sterova-admin/projects'
      preLoaderRoute: typeof SterovaAdminCmsProjectsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/results': {
      id: '/sterova-admin/_cms/results'
      path: '/results'
      fullPath: '/sterova-admin/results'
      preLoaderRoute: typeof SterovaAdminCmsResultsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/reviews': {
      id: '/sterova-admin/_cms/reviews'
      path: '/reviews'
      fullPath: '/sterova-admin/reviews'
      preLoaderRoute: typeof SterovaAdminCmsReviewsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/sessions': {
      id: '/sterova-admin/_cms/sessions'
      path: '/sessions'
      fullPath: '/sterova-admin/sessions'
      preLoaderRoute: typeof SterovaAdminCmsSessionsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/settings': {
      id: '/sterova-admin/_cms/settings'
      path: '/settings'
      fullPath: '/sterova-admin/settings'
      preLoaderRoute: typeof SterovaAdminCmsSettingsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/team': {
      id: '/sterova-admin/_cms/team'
      path: '/team'
      fullPath: '/sterova-admin/team'
      preLoaderRoute: typeof SterovaAdminCmsTeamRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/testimonials': {
      id: '/sterova-admin/_cms/testimonials'
      path: '/testimonials'
      fullPath: '/sterova-admin/testimonials'
      preLoaderRoute: typeof SterovaAdminCmsTestimonialsRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/posts/': {
      id: '/sterova-admin/_cms/posts/'
      path: '/posts'
      fullPath: '/sterova-admin/posts/'
      preLoaderRoute: typeof SterovaAdminCmsPostsIndexRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/posts/$id': {
      id: '/sterova-admin/_cms/posts/$id'
      path: '/posts/$id'
      fullPath: '/sterova-admin/posts/$id'
      preLoaderRoute: typeof SterovaAdminCmsPostsIdRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
    '/sterova-admin/_cms/posts/new': {
      id: '/sterova-admin/_cms/posts/new'
      path: '/posts/new'
      fullPath: '/sterova-admin/posts/new'
      preLoaderRoute: typeof SterovaAdminCmsPostsNewRouteImport
      parentRoute: typeof SterovaAdminCmsRoute
    }
  }
}

interface SterovaAdminCmsRouteChildren {
  SterovaAdminCmsAccessRoute: typeof SterovaAdminCmsAccessRoute
  SterovaAdminCmsBrandLinksRoute: typeof SterovaAdminCmsBrandLinksRoute
  SterovaAdminCmsCareersRoute: typeof SterovaAdminCmsCareersRoute
  SterovaAdminCmsCategoriesRoute: typeof SterovaAdminCmsCategoriesRoute
  SterovaAdminCmsChatAnalyticsRoute: typeof SterovaAdminCmsChatAnalyticsRoute
  SterovaAdminCmsChatLeadsRoute: typeof SterovaAdminCmsChatLeadsRoute
  SterovaAdminCmsConsultationsRoute: typeof SterovaAdminCmsConsultationsRoute
  SterovaAdminCmsDashboardRoute: typeof SterovaAdminCmsDashboardRoute
  SterovaAdminCmsEstimatesRoute: typeof SterovaAdminCmsEstimatesRoute
  SterovaAdminCmsMessagesRoute: typeof SterovaAdminCmsMessagesRoute
  SterovaAdminCmsNotificationsRoute: typeof SterovaAdminCmsNotificationsRoute
  SterovaAdminCmsProjectsRoute: typeof SterovaAdminCmsProjectsRoute
  SterovaAdminCmsResultsRoute: typeof SterovaAdminCmsResultsRoute
  SterovaAdminCmsReviewsRoute: typeof SterovaAdminCmsReviewsRoute
  SterovaAdminCmsSessionsRoute: typeof SterovaAdminCmsSessionsRoute
  SterovaAdminCmsSettingsRoute: typeof SterovaAdminCmsSettingsRoute
  SterovaAdminCmsTeamRoute: typeof SterovaAdminCmsTeamRoute
  SterovaAdminCmsTestimonialsRoute: typeof SterovaAdminCmsTestimonialsRoute
  SterovaAdminCmsPostsIdRoute: typeof SterovaAdminCmsPostsIdRoute
  SterovaAdminCmsPostsNewRoute: typeof SterovaAdminCmsPostsNewRoute
  SterovaAdminCmsPostsIndexRoute: typeof SterovaAdminCmsPostsIndexRoute
}

const SterovaAdminCmsRouteChildren: SterovaAdminCmsRouteChildren = {
  SterovaAdminCmsAccessRoute: SterovaAdminCmsAccessRoute,
  SterovaAdminCmsBrandLinksRoute: SterovaAdminCmsBrandLinksRoute,
  SterovaAdminCmsCareersRoute: SterovaAdminCmsCareersRoute,
  SterovaAdminCmsCategoriesRoute: SterovaAdminCmsCategoriesRoute,
  SterovaAdminCmsChatAnalyticsRoute: SterovaAdminCmsChatAnalyticsRoute,
  SterovaAdminCmsChatLeadsRoute: SterovaAdminCmsChatLeadsRoute,
  SterovaAdminCmsConsultationsRoute: SterovaAdminCmsConsultationsRoute,
  SterovaAdminCmsDashboardRoute: SterovaAdminCmsDashboardRoute,
  SterovaAdminCmsEstimatesRoute: SterovaAdminCmsEstimatesRoute,
  SterovaAdminCmsMessagesRoute: SterovaAdminCmsMessagesRoute,
  SterovaAdminCmsNotificationsRoute: SterovaAdminCmsNotificationsRoute,
  SterovaAdminCmsProjectsRoute: SterovaAdminCmsProjectsRoute,
  SterovaAdminCmsResultsRoute: SterovaAdminCmsResultsRoute,
  SterovaAdminCmsReviewsRoute: SterovaAdminCmsReviewsRoute,
  SterovaAdminCmsSessionsRoute: SterovaAdminCmsSessionsRoute,
  SterovaAdminCmsSettingsRoute: SterovaAdminCmsSettingsRoute,
  SterovaAdminCmsTeamRoute: SterovaAdminCmsTeamRoute,
  SterovaAdminCmsTestimonialsRoute: SterovaAdminCmsTestimonialsRoute,
  SterovaAdminCmsPostsIdRoute: SterovaAdminCmsPostsIdRoute,
  SterovaAdminCmsPostsNewRoute: SterovaAdminCmsPostsNewRoute,
  SterovaAdminCmsPostsIndexRoute: SterovaAdminCmsPostsIndexRoute,
}

const SterovaAdminCmsRouteWithChildren = SterovaAdminCmsRoute._addFileChildren(
  SterovaAdminCmsRouteChildren,
)

interface SterovaAdminRouteChildren {
  SterovaAdminCmsRoute: typeof SterovaAdminCmsRouteWithChildren
  SterovaAdminIndexRoute: typeof SterovaAdminIndexRoute
}

const SterovaAdminRouteChildren: SterovaAdminRouteChildren = {
  SterovaAdminCmsRoute: SterovaAdminCmsRouteWithChildren,
  SterovaAdminIndexRoute: SterovaAdminIndexRoute,
}

const SterovaAdminRouteWithChildren = SterovaAdminRoute._addFileChildren(
  SterovaAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EstimateRoute: EstimateRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartProjectRoute: StartProjectRoute,
  SterovaAdminRoute: SterovaAdminRouteWithChildren,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
